# Generated by Django 3.2.8 on 2022-03-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteAyar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site_gorunum',
            options={'verbose_name_plural': 'Site Görünüm '},
        ),
        migrations.AlterField(
            model_name='site_gorunum',
            name='logo',
            field=models.ImageField(upload_to='SiteAyar/site_gorunum'),
        ),
    ]
