# Generated by Django 3.2.8 on 2022-03-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteAyar', '0003_alter_site_gorunum_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_gorunum',
            name='alt_aciklama',
            field=models.CharField(default=False, max_length=150, verbose_name='alt açıklama'),
        ),
    ]
