# Generated by Django 3.2.8 on 2022-03-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteAyar', '0004_site_gorunum_alt_aciklama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site_gorunum',
            name='alt_aciklama',
        ),
        migrations.AddField(
            model_name='site_gorunum',
            name='alt_bilgi',
            field=models.CharField(blank=True, default=False, max_length=150, verbose_name='alt açıklama'),
        ),
    ]
