# Generated by Django 3.2.8 on 2022-03-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteAyar', '0005_auto_20220310_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_gorunum',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
