# Generated by Django 3.2.8 on 2022-03-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteAyar', '0008_ana_sayfa_seo_ayar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ana_sayfa_seo_ayar',
            options={'verbose_name_plural': 'Ana Sayfa Seo Ayar '},
        ),
    ]
