# Generated by Django 3.2.8 on 2022-03-11 15:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteAyar', '0009_alter_ana_sayfa_seo_ayar_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer_kontrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_header', models.CharField(default=True, max_length=50)),
                ('footer_text', ckeditor.fields.RichTextField()),
                ('footer_link', models.URLField()),
                ('alt_bilgi', models.CharField(blank=True, default=False, max_length=150, verbose_name='alt açıklama')),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('instagram', models.URLField()),
                ('youtube', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='site_gorunum',
            name='alt_bilgi',
        ),
    ]
