# Generated by Django 3.2.8 on 2022-03-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteAyar', '0010_auto_20220311_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer_kontrol',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
