# Generated by Django 3.2.8 on 2022-02-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0002_catagories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
