# Generated by Django 3.2.8 on 2022-02-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0006_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagories',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
