# Generated by Django 3.2.8 on 2022-02-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0008_auto_20220223_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
