# Generated by Django 3.2.8 on 2022-02-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0010_alter_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='kaynakca',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
