# Generated by Django 3.2.8 on 2022-02-23 14:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0011_blog_kaynakca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='kaynakca',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
