# Generated by Django 3.2.8 on 2022-02-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0012_alter_blog_kaynakca'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='yayimlanma_tarihi',
            field=models.DateTimeField(null=True),
        ),
    ]
