# Generated by Django 3.2.8 on 2022-02-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0013_blog_yayimlanma_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='yayimlanma_tarihi',
            field=models.DateTimeField(),
        ),
    ]
