# Generated by Django 3.2.8 on 2022-02-26 08:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0015_blog_yazar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_adi', models.CharField(max_length=200)),
                ('adi', models.CharField(max_length=200)),
                ('soyadi', models.CharField(max_length=200)),
                ('instagram_adresi', models.CharField(max_length=500)),
                ('facebook_adresi', models.CharField(max_length=500)),
                ('youtube_adresi', models.CharField(max_length=500)),
                ('twitter_adresi', models.CharField(max_length=500)),
                ('web_site', models.CharField(max_length=500)),
                ('iletisim_mail', models.CharField(max_length=500)),
                ('yazar_acıklama', ckeditor.fields.RichTextField()),
                ('yazar_resim', models.ImageField(upload_to='genelsayfalar')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='yazar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='genelsayfalar.yazar'),
        ),
    ]
