# Generated by Django 3.2.8 on 2022-02-26 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0016_auto_20220226_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='yazar',
        ),
    ]
