# Generated by Django 3.2.8 on 2022-02-26 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0017_remove_blog_yazar'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='yazar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='genelsayfalar.yazar'),
        ),
    ]
