# Generated by Django 3.2.8 on 2022-02-26 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genelsayfalar', '0018_blog_yazar'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazar',
            name='kullanıcı',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
