# Generated by Django 3.2.8 on 2022-02-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0019_yazar_kullanıcı'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yazar',
            old_name='kullanıcı',
            new_name='kullanici',
        ),
    ]
