# Generated by Django 3.2.8 on 2022-02-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0020_rename_kullanıcı_yazar_kullanici'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazar',
            name='facebook_adresi',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='yazar',
            name='iletisim_mail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='yazar',
            name='instagram_adresi',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='yazar',
            name='twitter_adresi',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='yazar',
            name='web_site',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='yazar',
            name='youtube_adresi',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
