# Generated by Django 3.2.8 on 2022-02-26 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genelsayfalar', '0021_auto_20220226_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazar',
            name='kullanici',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
