# Generated by Django 3.2.8 on 2022-02-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0022_alter_yazar_kullanici'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='yazar',
        ),
        migrations.DeleteModel(
            name='Yazar',
        ),
    ]
