# Generated by Django 3.2.8 on 2022-02-26 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genelsayfalar', '0023_auto_20220226_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='yazar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
