# Generated by Django 3.2.8 on 2022-02-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0025_auto_20220227_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yazar',
            options={},
        ),
        migrations.RemoveField(
            model_name='yazar',
            name='facebook_adresi',
        ),
        migrations.RemoveField(
            model_name='yazar',
            name='instagram_adresi',
        ),
        migrations.RemoveField(
            model_name='yazar',
            name='twitter_adresi',
        ),
        migrations.RemoveField(
            model_name='yazar',
            name='web_site',
        ),
        migrations.RemoveField(
            model_name='yazar',
            name='yazar_acıklama',
        ),
        migrations.RemoveField(
            model_name='yazar',
            name='yazar_resim',
        ),
        migrations.RemoveField(
            model_name='yazar',
            name='youtube_adresi',
        ),
    ]
