# Generated by Django 3.2.8 on 2022-02-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('genelsayfalar', '0026_auto_20220227_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='yazar',
        ),
        migrations.DeleteModel(
            name='Yazar',
        ),
    ]
