# Generated by Django 3.2.8 on 2022-02-27 11:53

import ckeditor.fields
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('genelsayfalar', '0027_auto_20220227_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yazar',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('instagram_adresi', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook_adresi', models.CharField(blank=True, max_length=500, null=True)),
                ('youtube_adresi', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter_adresi', models.CharField(blank=True, max_length=500, null=True)),
                ('web_site', models.CharField(blank=True, max_length=500, null=True)),
                ('yazar_acıklama', ckeditor.fields.RichTextField()),
                ('yazar_resim', models.ImageField(upload_to='genelsayfalar')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
