# Generated by Django 3.2.8 on 2022-02-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0028_yazar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yazar',
            options={'verbose_name': 'Yazar'},
        ),
    ]
