# Generated by Django 3.2.8 on 2022-02-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('genelsayfalar', '0029_alter_yazar_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Yazar',
        ),
    ]
