# Generated by Django 3.2.8 on 2022-02-27 17:24

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genelsayfalar', '0030_delete_yazar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_adresi', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook_adresi', models.CharField(blank=True, max_length=500, null=True)),
                ('youtube_adresi', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter_adresi', models.CharField(blank=True, max_length=500, null=True)),
                ('web_site', models.CharField(blank=True, max_length=500, null=True)),
                ('yazar_acıklama', ckeditor.fields.RichTextField(blank=True)),
                ('yazar_resim', models.ImageField(upload_to='genelsayfalar')),
                ('yazar_adi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='yazar adi')),
            ],
        ),
    ]
