# Generated by Django 3.2.8 on 2022-02-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0031_yazar'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazar',
            name='isim',
            field=models.CharField(default='kadir', max_length=500, verbose_name='yazar adı ve soyadı'),
        ),
    ]
