# Generated by Django 3.2.8 on 2022-02-28 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0032_yazar_isim'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogun_yazari',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='genelsayfalar.yazar', verbose_name='blogun yazarı'),
        ),
    ]
