# Generated by Django 3.2.8 on 2022-02-28 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0035_alter_blog_blogun_yazari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogun_yazari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genelsayfalar.yazar', verbose_name='blogun yazarı'),
        ),
    ]
