# Generated by Django 3.2.8 on 2022-02-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0036_alter_blog_blogun_yazari'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blogun_yazari',
        ),
    ]
