# Generated by Django 3.2.8 on 2022-03-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0038_blog_blogun_yazari'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazar',
            name='yazar_pozisyonu',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
