# Generated by Django 3.2.8 on 2022-03-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0040_blog_blogun_kategorisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagories',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
