# Generated by Django 3.2.8 on 2022-03-01 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0041_catagories_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yazar',
            old_name='yazar_acıklama',
            new_name='yazar_aciklama',
        ),
    ]
