# Generated by Django 3.2.8 on 2022-03-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0042_rename_yazar_acıklama_yazar_yazar_aciklama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazar',
            name='facebook_adresi',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='yazar',
            name='instagram_adresi',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='yazar',
            name='twitter_adresi',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='yazar',
            name='web_site',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='yazar',
            name='youtube_adresi',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
