# Generated by Django 3.2.8 on 2022-03-03 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0044_auto_20220302_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('image', models.ImageField(upload_to='genelsayfalar/youtube')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktif İçerik')),
                ('date', models.DateField()),
                ('url', models.URLField(verbose_name='Videonun Linki')),
                ('kategori', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='genelsayfalar.catagories')),
            ],
        ),
    ]
