# Generated by Django 3.2.8 on 2022-03-03 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0045_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='date',
            field=models.DateField(verbose_name='Yüklenme Zamanı'),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='image',
            field=models.ImageField(upload_to='genelsayfalar/youtube', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genelsayfalar.catagories'),
        ),
    ]
