# Generated by Django 3.2.8 on 2022-03-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0047_kitap_onerileri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='manset',
            field=models.BooleanField(default=False, help_text='ÖNCE AKTİF OLAN MANSET BLOGUNU İNAKTİF HALE GETİRİN', verbose_name='Manşet Alanında  Göster'),
        ),
    ]
