# Generated by Django 3.2.8 on 2022-03-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0048_alter_blog_manset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Makale Ekle'},
        ),
        migrations.AlterModelOptions(
            name='catagories',
            options={'verbose_name_plural': 'Katagoriler'},
        ),
        migrations.AlterModelOptions(
            name='kitap_onerileri',
            options={'verbose_name_plural': 'Kitap Önerileri'},
        ),
        migrations.AlterModelOptions(
            name='yazar',
            options={'verbose_name_plural': 'Yazarlar Hakkında'},
        ),
        migrations.AlterModelOptions(
            name='youtube',
            options={'verbose_name_plural': 'Youtube Ekle'},
        ),
    ]
