# Generated by Django 3.2.8 on 2022-03-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0049_auto_20220309_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagories',
            name='meta_description',
            field=models.CharField(default=True, max_length=160, verbose_name='max 160 karekter uzunluğunda olmalıdır'),
        ),
        migrations.AddField(
            model_name='catagories',
            name='meta_keywords',
            field=models.CharField(default=True, max_length=100, verbose_name='aralarına virgül konulacak şekilde max 5 anahtar kelime giriniz'),
        ),
        migrations.AddField(
            model_name='catagories',
            name='meta_title',
            field=models.CharField(default='<django.db.models.fields.CharField>|Evrim Işığı', max_length=150),
        ),
    ]
