# Generated by Django 3.2.8 on 2022-03-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0050_auto_20220310_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagories',
            name='meta_description',
            field=models.CharField(default=True, help_text='max 160 karekter uzunluğunda olmalıdır', max_length=160, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='catagories',
            name='meta_keywords',
            field=models.CharField(default=True, help_text='aralarına virgül konulacak şekilde max 5 anahtar kelime giriniz', max_length=100, verbose_name='meta keywords'),
        ),
    ]
