# Generated by Django 3.2.8 on 2022-03-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0051_auto_20220310_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagories',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='catagories',
            name='meta_description',
            field=models.CharField(help_text='max 160 karekter uzunluğunda olmalıdır', max_length=160, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='catagories',
            name='meta_keywords',
            field=models.CharField(db_index=True, help_text='aralarına virgül konulacak şekilde max 5 anahtar kelime giriniz', max_length=100, verbose_name='meta keywords'),
        ),
        migrations.AlterField(
            model_name='catagories',
            name='meta_title',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='catagories',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
