# Generated by Django 3.2.8 on 2022-03-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0052_auto_20220311_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_seo',
            field=models.CharField(default=True, max_length=70),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.CharField(default=False, help_text='max 160 karekter uzunluğunda olmalıdır', max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_keywords',
            field=models.CharField(db_index=True, default=False, help_text='aralarına virgül konulacak şekilde max 5 anahtar kelime giriniz', max_length=100, verbose_name='Anahtar Kelimeler'),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(db_index=True, default=False, help_text="Buraya yazılan alan sayfa başlığıdır arama motorlarında görünecektir sonuna  '|Site Adı ' eklemeyi unutmayın... ", max_length=150, verbose_name='Meta Title'),
        ),
    ]
