# Generated by Django 3.2.8 on 2022-03-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genelsayfalar', '0054_yazar_yazar_resim_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(db_index=True, default=False, help_text="Buraya yazılan alan sayfa başlığıdır arama motorlarında görünecektir başlık kısmını da ekleyebilirsiniz max=150 karakter ve  sonuna  '|Site Adı ' eklemeyi unutmayın... ", max_length=150, verbose_name='Meta Title'),
        ),
    ]
